### ISSUE TITLE
I am getting issues

### ISSUE THREAD

**Issue by soumendrapatra** [sleepyzardo/poketwo-event-completer#2]
![image](https://github.com/sleepyzardo/poketwo-event-completer/assets/153013238/19d620dc-2238-4f57-996a-803ffbd0af0e)
what to do next?
Also tell me where to put tokens and channel id particularly

**Comment by sleepyzardo** [comment]
Hi! Pls try `pip uninstall discord discord.py -y` and then `pip install discord.py-self`
