### ISSUE TITLE
question for you

### ISSUE THREAD

**Issue by pk2luvr** [sleepyzardo/poketwo-event-completer#3]
heya, i used your event completer during the anniversary event, it was amazing btw. i was curious with the new event if you had any plans to make a minisport completer script as well (i know it just released) i saw your github link in OS origonally, it helped me a lot during the anniversary ev lol. i tried to message you on discord but i was unable to send it due to us not sharing a server

**Comment by sleepyzardo** [comment]
Sorry for the late reply, But I did indeed have plans and it's done! Only for paid users though.
